// Mock 데이터 - 로그인 테스트용 최소 데이터
export const mockAdminUser = {
  id: 1,
  name: "관리자",
  email: "admin@hotel.com",
  role: "admin",
};

export const mockDashboardStats = {
  todayBookings: 15,
  totalRevenue: 12500000,
  activeHotels: 45,
  newUsers: 8,
  chartData: {
    labels: ["1월", "2월", "3월", "4월", "5월", "6월"],
    revenue: [2000000, 2500000, 2200000, 2800000, 3000000, 3200000],
    bookings: [45, 58, 52, 67, 72, 78],
  },
  recentBookings: [
    {
      id: 1,
      hotelName: "서울 그랜드 호텔",
      userName: "홍길동",
      amount: 150000,
      status: "confirmed",
      createdAt: new Date().toISOString(),
    },
    {
      id: 2,
      hotelName: "부산 리조트",
      userName: "김철수",
      amount: 200000,
      status: "pending",
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ],
  recentUsers: [
    {
      id: 1,
      name: "이영희",
      email: "lee@example.com",
      status: "active",
      createdAt: new Date().toISOString(),
    },
    {
      id: 2,
      name: "박민수",
      email: "park@example.com",
      status: "active",
      createdAt: new Date(Date.now() - 7200000).toISOString(),
    },
  ],
  recentReviews: [
    {
      id: 1,
      hotelName: "서울 그랜드 호텔",
      userName: "홍길동",
      rating: 5,
      createdAt: new Date().toISOString(),
    },
    {
      id: 2,
      hotelName: "부산 리조트",
      userName: "김철수",
      rating: 4,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ],
};

// Mock 호텔 데이터
export const mockHotels = [
  {
    id: 1,
    name: "서울 그랜드 호텔",
    address: "서울시 강남구 테헤란로 123",
    rating: 4.5,
    price: 150000,
    status: "approved",
    createdAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: 2,
    name: "부산 리조트",
    address: "부산시 해운대구 해운대해변로 456",
    rating: 4.8,
    price: 200000,
    status: "pending",
    createdAt: new Date("2024-01-20").toISOString(),
  },
  {
    id: 3,
    name: "제주 오션뷰 호텔",
    address: "제주시 연동 789",
    rating: 4.2,
    price: 180000,
    status: "active",
    createdAt: new Date("2024-01-10").toISOString(),
  },
  {
    id: 4,
    name: "경주 힐튼 호텔",
    address: "경주시 불국로 321",
    rating: 4.7,
    price: 220000,
    status: "approved",
    createdAt: new Date("2024-01-18").toISOString(),
  },
  {
    id: 5,
    name: "인천 공항 호텔",
    address: "인천시 중구 공항로 654",
    rating: 3.9,
    price: 120000,
    status: "rejected",
    createdAt: new Date("2024-01-12").toISOString(),
  },
];

// Mock 예약 데이터
export const mockBookings = [
  {
    id: 1,
    hotelName: "서울 그랜드 호텔",
    userName: "홍길동",
    userEmail: "hong@example.com",
    checkIn: new Date("2024-02-01").toISOString(),
    checkOut: new Date("2024-02-03").toISOString(),
    guests: { adults: 2, children: 1 },
    amount: 300000,
    status: "confirmed",
    createdAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: 2,
    hotelName: "부산 리조트",
    userName: "김철수",
    userEmail: "kim@example.com",
    checkIn: new Date("2024-02-05").toISOString(),
    checkOut: new Date("2024-02-07").toISOString(),
    guests: { adults: 2, children: 0 },
    amount: 400000,
    status: "pending",
    createdAt: new Date("2024-01-20").toISOString(),
  },
  {
    id: 3,
    hotelName: "제주 오션뷰 호텔",
    userName: "이영희",
    userEmail: "lee@example.com",
    checkIn: new Date("2024-01-25").toISOString(),
    checkOut: new Date("2024-01-27").toISOString(),
    guests: { adults: 1, children: 0 },
    amount: 360000,
    status: "completed",
    createdAt: new Date("2024-01-10").toISOString(),
  },
  {
    id: 4,
    hotelName: "경주 힐튼 호텔",
    userName: "박민수",
    userEmail: "park@example.com",
    checkIn: new Date("2024-02-10").toISOString(),
    checkOut: new Date("2024-02-12").toISOString(),
    guests: { adults: 3, children: 1 },
    amount: 440000,
    status: "cancelled",
    createdAt: new Date("2024-01-18").toISOString(),
  },
];

// Mock 사용자 데이터
export const mockUsers = [
  {
    id: 1,
    name: "홍길동",
    email: "hong@example.com",
    phone: "010-1234-5678",
    role: "user",
    status: "active",
    createdAt: new Date("2023-12-01").toISOString(),
  },
  {
    id: 2,
    name: "김철수",
    email: "kim@example.com",
    phone: "010-2345-6789",
    role: "business",
    status: "active",
    createdAt: new Date("2023-12-15").toISOString(),
  },
  {
    id: 3,
    name: "이영희",
    email: "lee@example.com",
    phone: "010-3456-7890",
    role: "user",
    status: "inactive",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: 4,
    name: "박민수",
    email: "park@example.com",
    phone: "010-4567-8901",
    role: "user",
    status: "suspended",
    createdAt: new Date("2024-01-10").toISOString(),
  },
  {
    id: 5,
    name: "정수진",
    email: "jung@example.com",
    phone: "010-5678-9012",
    role: "business",
    status: "active",
    createdAt: new Date("2024-01-20").toISOString(),
  },
];

// Mock 리뷰 데이터
export const mockReviews = [
  {
    id: 1,
    hotelId: 1,
    hotelName: "서울 그랜드 호텔",
    userName: "홍길동",
    userEmail: "hong@example.com",
    rating: 5,
    content: "정말 깨끗하고 서비스가 훌륭했습니다. 다음에도 또 이용하고 싶어요!",
    reported: false,
    createdAt: new Date("2024-01-20").toISOString(),
  },
  {
    id: 2,
    hotelId: 2,
    hotelName: "부산 리조트",
    userName: "김철수",
    userEmail: "kim@example.com",
    rating: 4,
    content: "해변이 가까워서 좋았습니다. 다만 조식이 좀 아쉬웠어요.",
    reported: false,
    createdAt: new Date("2024-01-18").toISOString(),
  },
  {
    id: 3,
    hotelId: 3,
    hotelName: "제주 오션뷰 호텔",
    userName: "이영희",
    userEmail: "lee@example.com",
    rating: 3,
    content: "시설은 괜찮은데 직원 서비스가 별로였습니다.",
    reported: true,
    createdAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: 4,
    hotelId: 1,
    hotelName: "서울 그랜드 호텔",
    userName: "박민수",
    userEmail: "park@example.com",
    rating: 5,
    content: "완벽한 숙박이었습니다! 강력 추천합니다.",
    reported: false,
    createdAt: new Date("2024-01-12").toISOString(),
  },
];

// Mock 쿠폰 데이터
export const mockCoupons = [
  {
    id: 1,
    code: "WELCOME2024",
    name: "신규 가입 환영 쿠폰",
    discountType: "percentage",
    discountValue: 10,
    startDate: new Date("2024-01-01").toISOString(),
    endDate: new Date("2024-12-31").toISOString(),
    usageLimit: 1000,
    usedCount: 245,
    isActive: true,
    createdAt: new Date("2023-12-20").toISOString(),
  },
  {
    id: 2,
    code: "SUMMER50000",
    name: "여름 특가 쿠폰",
    discountType: "fixed",
    discountValue: 50000,
    startDate: new Date("2024-06-01").toISOString(),
    endDate: new Date("2024-08-31").toISOString(),
    usageLimit: 500,
    usedCount: 500,
    isActive: true,
    createdAt: new Date("2024-05-15").toISOString(),
  },
  {
    id: 3,
    code: "WEEKEND20",
    name: "주말 할인 쿠폰",
    discountType: "percentage",
    discountValue: 20,
    startDate: new Date("2024-01-01").toISOString(),
    endDate: new Date("2024-03-31").toISOString(),
    usageLimit: null,
    usedCount: 89,
    isActive: false,
    createdAt: new Date("2023-12-25").toISOString(),
  },
  {
    id: 4,
    code: "FIRST10000",
    name: "첫 예약 할인",
    discountType: "fixed",
    discountValue: 10000,
    startDate: new Date("2024-02-01").toISOString(),
    endDate: new Date("2024-02-29").toISOString(),
    usageLimit: 200,
    usedCount: 156,
    isActive: true,
    createdAt: new Date("2024-01-25").toISOString(),
  },
];
